local speaker = peripheral.find("speaker")
if speaker then
    speaker.playNote("bit")
end
print("CC Tweaked BIOS")
print("Copyright 2012-2022")
print("Powered by Betterboot. Made by Nexus ")
print(("Memory Test: %dMB"):format(fs.getCapacity("")/1048576))
print("OK")
print("Initilize Peripherals...")
print("Keyboard Input")
print("Mouse Input")
print("Monitors")
print("Speakers")
print("Disk Drives")
print("Printers")
print("Peripherals Init Completed")
term.clear()
term.setCursorPos(1,1)

print("Starting Craft OS...")
print("HIMEM is testing extended memory...")
print("Done!")
print("Searching for Input...")
print("Searching for Storage Device...")
print("Searching for External Devices...")
print("Initilizing Software")
print("Done!")
